DEFAULT_EVALUATION_MODEL_NAME = "tenon-fit-evaluator"
DEFAULT_EVALUATION_MODEL_VERSION = "2026-03-12"
DEFAULT_EVALUATION_PROMPT_VERSION = "fit-profile-v1"
DEFAULT_RUBRIC_VERSION = "rubric-v1"

__all__ = [
    "DEFAULT_EVALUATION_MODEL_NAME",
    "DEFAULT_EVALUATION_MODEL_VERSION",
    "DEFAULT_EVALUATION_PROMPT_VERSION",
    "DEFAULT_RUBRIC_VERSION",
]
