DEFAULT_EVALUATION_MODEL_NAME = "gpt-5.5"
DEFAULT_EVALUATION_MODEL_VERSION = "gpt-5.5"
DEFAULT_EVALUATION_PROMPT_VERSION = "winoe-ai-pack-v4:winoeReport"
DEFAULT_RUBRIC_VERSION = "winoe-ai-pack-v4:winoeReport:rubric"

__all__ = [
    "DEFAULT_EVALUATION_MODEL_NAME",
    "DEFAULT_EVALUATION_MODEL_VERSION",
    "DEFAULT_EVALUATION_PROMPT_VERSION",
    "DEFAULT_RUBRIC_VERSION",
]
