WORKSPACE_CLEANUP_STATUS_PENDING = "pending"
WORKSPACE_CLEANUP_STATUS_ARCHIVED = "archived"
WORKSPACE_CLEANUP_STATUS_DELETED = "deleted"
WORKSPACE_CLEANUP_STATUS_FAILED = "failed"

WORKSPACE_CLEANUP_TERMINAL_STATUSES = {
    WORKSPACE_CLEANUP_STATUS_ARCHIVED,
    WORKSPACE_CLEANUP_STATUS_DELETED,
}
