"""Shared AI runtime helpers for prompt packs, overrides, and structured outputs."""

from .ai_output_models import (
    AggregatedWinoeReportOutput,
    CodespacePatchProposal,
    DayReviewerOutput,
    ScenarioGenerationOutput,
)
from .ai_policy_snapshot_service import (
    AIPolicySnapshotError,
    build_ai_policy_snapshot,
    build_required_snapshot_prompt,
    build_snapshot_prompt,
    compute_ai_policy_snapshot_digest,
    get_agent_policy_snapshot,
    get_candidate_settings_from_snapshot,
    require_agent_policy_snapshot,
    require_agent_runtime,
    require_ai_policy_snapshot,
    require_candidate_settings_from_snapshot,
)
from .ai_prompt_models import (
    AI_AGENT_KEYS,
    AI_PROMPT_OVERRIDE_KEYS,
    AgentPromptOverride,
    PromptOverrideSet,
    merge_prompt_override_payloads,
    normalize_prompt_override_payload,
)
from .ai_prompt_pack_service import (
    PROMPT_PACK_VERSION,
    build_prompt_pack_entry,
)
from .ai_prompt_resolution_service import resolve_prompt_layers
from .ai_runtime_config_service import (
    AI_RUNTIME_MODE_DEMO,
    AI_RUNTIME_MODE_REAL,
    AI_RUNTIME_MODE_TEST,
    AIFeatureConfig,
    allow_demo_or_test_mode,
    require_real_mode,
    resolve_codespace_specializer_config,
    resolve_runtime_mode,
    resolve_scenario_generation_config,
    resolve_transcription_config,
    resolve_winoe_report_aggregator_config,
    resolve_winoe_report_code_implementation_config,
    resolve_winoe_report_day1_config,
    resolve_winoe_report_day4_config,
    resolve_winoe_report_day5_config,
    resolve_winoe_report_day23_config,
)

__all__ = [
    "AIFeatureConfig",
    "AI_AGENT_KEYS",
    "AI_PROMPT_OVERRIDE_KEYS",
    "AI_RUNTIME_MODE_DEMO",
    "AI_RUNTIME_MODE_REAL",
    "AI_RUNTIME_MODE_TEST",
    "AIPolicySnapshotError",
    "AggregatedWinoeReportOutput",
    "AgentPromptOverride",
    "CodespacePatchProposal",
    "DayReviewerOutput",
    "PROMPT_PACK_VERSION",
    "PromptOverrideSet",
    "ScenarioGenerationOutput",
    "allow_demo_or_test_mode",
    "build_ai_policy_snapshot",
    "build_prompt_pack_entry",
    "build_required_snapshot_prompt",
    "build_snapshot_prompt",
    "compute_ai_policy_snapshot_digest",
    "get_agent_policy_snapshot",
    "get_candidate_settings_from_snapshot",
    "merge_prompt_override_payloads",
    "normalize_prompt_override_payload",
    "require_agent_policy_snapshot",
    "require_agent_runtime",
    "require_ai_policy_snapshot",
    "require_candidate_settings_from_snapshot",
    "require_real_mode",
    "resolve_codespace_specializer_config",
    "resolve_winoe_report_aggregator_config",
    "resolve_winoe_report_code_implementation_config",
    "resolve_winoe_report_day1_config",
    "resolve_winoe_report_day23_config",
    "resolve_winoe_report_day4_config",
    "resolve_winoe_report_day5_config",
    "resolve_prompt_layers",
    "resolve_runtime_mode",
    "resolve_scenario_generation_config",
    "resolve_transcription_config",
]
